---
- name: "Stage : Setup Software & Configuration On Node Master"
  hosts: dev_cicd_node_masters
  become: yes
  tasks:
    - name: Create Policy To Deny Everything And Enable UFW
      community.general.ufw:
        state: enabled
        policy: deny
    - name: Create Policy To Allow Any Traffic To TCP Port 8080
      community.general.ufw:
        rule: allow
        port: '8080'
        proto: tcp
    - name: Create Policy To Allow Any Traffic To TCP Port 22
      community.general.ufw:
        rule: allow
        port: '22'
        proto: tcp
    - name: Create & Add Jenkins Stable Release Apt Key
      ansible.builtin.apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present
    - name: Start Jenkins Service
      systemd:
        name: jenkins
        state: restarted
        enabled: yes