- name: "Stage : Setup Software & Configuration On Node Worker"
  hosts: dev_cicd_node_workers
  become: yes

  tasks:
    - name: Create Policy To Allow Everything And Enable UFW
      community.general.ufw:
        state: enabled
        policy: deny
    - name: Create Policy To Allow Any Traffic To TCP Port 22
      community.general.ufw:
        rule: allow
        port: '22'
        proto: tcp
    - name: Delete & Remove Any Docker Engine Installation
      apt:
        name:
          - docker 
          - docker-engine 
          - docker.io 
          - containerd 
          - runc 
        state: absent
    - name: Create & Add Docker-CE Apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Create & Add Docker-CE Deb Repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: Install Docker
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
    - name: Create & Add Docker Group
      group:
        name: docker
        state: present
    - name: Create & Add $USER To Docker Group
      user: 
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
    - name: Update & Execute SSH Reset In Order To Reflect The $USER Group Changes
      meta: reset_connection
    - name: Start Docker service
      systemd:
        name: docker
        state: restarted   
        enabled: yes


    - name: Install Prerequisites For Maven 3.8.6
      apt:
        name:
          - wget
          - tar
        state: present
        update_cache: yes
    - name: Create directory for Maven installation
      file:
        path: /opt/maven
        state: directory
    - name: Download Maven 3.8.x binary
      get_url:
        url: "https://archive.apache.org/dist/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz"
        dest: /tmp/apache-maven-3.8.6-bin.tar.gz
    - name: Create & Extract Maven Binary
      unarchive:
        src: /tmp/apache-maven-3.8.6-bin.tar.gz
        dest: /opt/maven/
        remote_src: yes
    - name: Create symbolic link for Maven
      file:
        src: /opt/maven/apache-maven-3.8.6
        dest: /opt/maven/latest
        state: link
    - name: Create Maven environment variables
      copy:
        dest: /etc/profile.d/maven.sh
        content: |
          export MAVEN_HOME=/opt/maven/latest
          export PATH=$PATH:$MAVEN_HOME/bin
        mode: '0644'
    - name: Update Maven environment variables and verify Maven version
      shell: |
        export MAVEN_HOME=/opt/maven/latest
        export PATH=$PATH:$MAVEN_HOME/bin
        mvn -version
      register: maven_version
      environment:
        MAVEN_HOME: /opt/maven/latest
        PATH: "{{ ansible_env.PATH }}:/opt/maven/latest/bin"
        
