---
- name: "Stage : Setup Software & Configuration On Node Master"
  hosts: dev_cicd_node_masters
  become: yes
  tasks:
    - name: Create Policy To Deny Everything And Enable UFW
      community.general.ufw:
        state: enabled
        policy: deny
    - name: Create Policy To Allow Any Traffic To TCP Port 8080
      community.general.ufw:
        rule: allow
        port: '8080'
        proto: tcp
    - name: Create Policy To Allow Any Traffic To TCP Port 22
      community.general.ufw:
        rule: allow
        port: '22'
        proto: tcp
    - name: Create & Add Jenkins Stable Release Apt Key
      ansible.builtin.apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present
    - name: Create & Add Jenkins Stable Release Deb Repository
      ansible.builtin.apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present
    - name: Install Jenkins
      apt:
        name:
          - jenkins=2.401.3
    - name: Stop Jenkins Systemd
      systemd:
        name: jenkins
        state: stopped
    - name: Delete JENKINS_HOME directory
      file:
        state: absent
        path: /var/lib/jenkins
    - name: Create Directories For Jenkins
      file:
        path: "{{ item }}"
        state: directory
        owner: jenkins
        group: jenkins
        recurse: yes
      with_items:
        - '/var/cache/jenkins/tmp'
        - '/var/cache/jenkins/heapdumps'
        - '/var/lib/jenkins'
    - name: Create Directories For Systemd Override File
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        recurse: yes
      with_items:
        - '/etc/systemd/system/jenkins.service.d'

    - name: Start Jenkins Service
      systemd:
        name: jenkins
        state: restarted
        enabled: yes